### ISSUE TITLE
Using same factory overwrites multiple assigned instances

### ISSUE THREAD

**Issue by doutatsu** [rosiejs/rosie#100]
```js
  import BookFactory from '../factories/Book';
  const entry1 = BookFactory.build({ id: '1', attributes: { title: 'Journal' } }); 
  const entry2 = BookFactory.build({ id: '2', attributes: { title: 'Book'} });
```

I've been seeing this weird behaviour for awhile now and trying to understand if it's Rosie or something else. I am trying to create 2 separate objects, from the same factory, but with different attributes. Hence the code above.

But, after defining `entry2`, `entry1` title gets's overwritten to `Book` as well... Interesting `id` gets assigned correctly, but nested attributes is what causing the problem...

**Comment by eventualbuddha** [comment]
Can you provide a minimal example on codesandbox.io or something?

**Comment by doutatsu** [comment]
Sorry, didn't get a chance to do that and frankly, don't feel like taking the time to do it. There are some other issues with the library, so instead, I decided to switch to [Fishery made by ThoughtBot](https://github.com/thoughtbot/fishery), which has none of the issues I find with Rosie. 

Sorry for not being helpful about this, it's been a great library otherwise

**Comment by luongs3** [comment]
I got the same issue here. If you modify 1 property in an object inside, It will override forever. Eg:
```
  import BookFactory from '../factories/Book';
  const entry1 = BookFactory.build({ id: '1', attributes: { title: 'Journal' } }); 
  const entry2 = BookFactory.build({ id: '2', });
```
when build `entry1`, I override `attributes => title`.
After that I build `entry2`, don't pass value for `attributes`. But `entry2.attributes.title` still equals 'Journal'.
Already use `Factory.resetAll()`, but doesn't work.
@eventualbuddha could you check this.

**Comment by eventualbuddha** [comment]
I tried this, and it seemed to work as expected. Can you provide an example that behaves as you say?

```ts
const { Factory } = require("rosie");

const BookFactory = new Factory();
const entry1 = BookFactory.build({ id: "1", attributes: { title: "Journal" } });
const entry2 = BookFactory.build({ id: "2" });

console.log({ entry1, entry2 });
/*
{
  entry1: { id: '1', attributes: { title: 'Journal' } },
  entry2: { id: '2' }
}
*/
```
