### ISSUE TITLE
A way to reset sequence for Factory before running each Jest test

### ISSUE THREAD

**Issue by quarryman** [rosiejs/rosie#108]
HI there.
Given I have a Factory defined and exported, what is proper way to get new Factory instance/reset sequence before each test?

**Comment by KyleW** [comment]
I believe this is the same thing as pr #73 . I'm not sure who's maintaining this library right now, but it seems like a worthwhile change.

**Comment by eventualbuddha** [comment]
@quarryman how's this look? https://github.com/rosiejs/rosie/pull/109

**Comment by quarryman** [comment]
This looks perfectly fine, @eventualbuddha 
Can you please merge it anytime soon?

**Comment by eventualbuddha** [comment]
@quarryman published in v2.1.0
