### ISSUE TITLE
How to build recursively?

### ISSUE THREAD

**Issue by sangdth** [rosiejs/rosie#118]
Hi, I have a case where I want to create some items recursively. Like this:
```
[
    { id: '1', label: 'Item 1', children: [] },
    { id: '2', label: 'Item 1', children: [
        { id: '2-1', label: 'Item 2-1', children: [] },
        { id: '2-2', label: 'Item 2-1', children: [
            { id: '2-1-1', label: 'Item 2-1-1', children: [] },
        ] },
    ] },
]
```

I tried with:
```
export const MenuValueFactory = new Factory<Value>()
  .sequence('label', (i) => `Menu Item ${i}`)
  .sequence('slug', (i) => `menu-item-${i}`)
  .attrs({
    id: () => uuidv4(),
    children: () => MenuValueFactory.buildList(3),
  });
```

Then I got `RangeError: Maximum call stack size exceeded`  (not surprise 🙈 )

I tried to Google and search issues here but have no luck. Can someone help, please?

Thanks so much.

**Comment by eventualbuddha** [comment]
If _every_ object that gets built is going to have three children, then you’ll be trying to build an infinite number whenever you build even one. Building values is not lazy, so it has to be able to finish upfront. If you used something like `children: () => MenuValueFactory.buildList(Math.floor(Math.random() * 3))` then you’d end up with something that is likely not infinite. You could also use options to pass down a “child count” that decreases with each generation, so to speak.

**Comment by sangdth** [comment]
Thanks @eventualbuddha, I managed to make it works by calling it separately, not beautiful but fulfil my need
```
export const MenuValueFactory = new Factory<OptionValue>()
  .sequence('label', (i) => `${lorem.words()} ${i}`)
  .sequence('slug', (i) => `${lorem.slug()}-${i}`)
  .attrs({
    id: () => uuidv4(),
    children: [],
  });
  
export const MenuFactory = new Factory<MenuOption>()
  .attrs(baseAttributes)
  .attrs({
    site_id: () => uuidv4(),
    key: OptionKey.Menu,
    value: () => MenuValueFactory.buildList(5, {
      children: (() => MenuValueFactory.buildList(3))(),
    }),
  });
```
