### ISSUE TITLE
Error occurs when try to build using dependent attributes that are not defined

### ISSUE THREAD

**Issue by oveddan** [rosiejs/rosie#46]
I want to have a factory as such:

```javascript
var settingsForThemes = {
   'long': {
       duration: 30,
       content: 'a longer theme'
   },
   'short': {
       duration: 10,
       content: 'a shorter theme'
   }
}

var factory = new Factory()
                    .attr('settings', ['theme'], function(theme) {
                         return settingsForThemes[them]
                     }) 
```

When I try to build using this factory, by passing it a theme:

```javascript
var built = factory.build({theme: 'long'})
```

You get an error:

> TypeError: Cannot read property 'dependencies' of undefined
> at Object.Factory._alwaysCallBuilder (.../node_modules/rosie/src/rosie.js:230:20)

If I define the attribute `theme` on the factory, the error doesn't occur.  However, I don't want to define that attribute, because it should never exist on the object.  If extra attributes are added to the object that shouldn't be there, other parts of the program throw an error.

You should be able to define attributes that depend on other attributes that haven't necessarily been defined on the factory.

**Comment by kylezeeuwen** [comment]
@oveddan 

You can do this with the existing code base (at v1.3.0) by specifying theme as an option.
Note the function signature for build is build(attributes, options). Options are not included in the output but are used to generate the attributes. See the working code example below:

    const Factory = require('rosie').Factory;

    var settingsForThemes = {
       'long': {
           duration: 30,
           content: 'a longer theme'
       },
       'short': {
           duration: 10,
           content: 'a shorter theme'
       }
    }

    var factory = new Factory()
      .option('theme', 'long')
      .attr('settings', ['theme'], function(theme) {
        return settingsForThemes[theme]
      });

    console.log(factory.build());
    console.log(factory.build({}, {theme: 'short'}));
    console.log(factory.build({}, {theme: 'long'}));

    // OUTPUT
    // { settings: { duration: 30, content: 'a longer theme' } }
    // { settings: { duration: 10, content: 'a shorter theme' } }
    // { settings: { duration: 30, content: 'a longer theme' } }

**Comment by eventualbuddha** [comment]
As @kylezeeuwen pointed out, this is currently possible and now better documented, so I'm closing.
