### ISSUE TITLE
how to exclude attributes when inheriting?

### ISSUE THREAD

**Issue by Alino** [rosiejs/rosie#58]
let's say I have this example factory definition

```javascript
Factory.define('example')
.sequence('id')
.attr('ignored', false)
.attr('taskId', '666')
```

now I want to define another factory and inherit from 'example' factory
but removing some attributes

```javascript
Factory.define('second-example').extend('example')
.removeAttr('ignored')
```

the ```.removeAttr``` method does not exist, is there such concept? or how could I achieve my goal?

**Comment by eventualbuddha** [comment]
You could reverse the "inheritance", or you could define an after build step for the second one that arbitrarily edits the object.
