### ISSUE TITLE
Add an option to merge properties instead of overriding?

### ISSUE THREAD

**Issue by entropitor** [rosiejs/rosie#60]
E.g. if you can pass a merging property to `.build()` that will merge the attributes with the ones from the factory. E.g. If the factory would return `{foo: {bar: false, baz: true}}` and you pass `{foo: {baz: 3}}` that it will return `{foo: {bar: false, baz: 3}}`

**Comment by eventualbuddha** [comment]
Do you have a specific use case for this? This seems like a specialized use case to me, but maybe I’m missing something.

**Comment by entropitor** [comment]
To update fields deeper down the object tree? So you don't need to use a factory to create a sub-object and pass that along, you can just change the field and the main factory will use the other factory to generate the properties

**Comment by eventualbuddha** [comment]
This seems like something that can easily be done outside rosie, and isn’t likely that common. You can just use lodash `extend`, right?
