### ISSUE TITLE
Support or Recommended Alternative

### ISSUE THREAD

**Issue by firebait** [rosiejs/rosie#62]
Just writing to see if there is any intention of long  term support or a recommended alternative to this library. The factory pattern is something I like but if it has fallen out of favor I would like to see what would be a nice alternative.

**Comment by firebait** [comment]
I guess we should fork this project if we want to support it?

**Comment by eventualbuddha** [comment]
Is there something you’re looking for that is missing? Have you submitted a bug report or pull request that is being ignored?

**Comment by firebait** [comment]
Not really, just saw that the las commit was in 2016 so we were wondering if the project was abandoned as we use this library for our company’s test. Mainly want to know if we find an issue or if we have a feature request this will still be the right avenue for support.

**Comment by eventualbuddha** [comment]
It’s maintained by volunteers, primarily me these days. Square, my employer, uses it for their largest web product so I think we’re likely to keep it working. Can’t promise much though 😝

**Comment by eventualbuddha** [comment]
I'm closing this since I just put a bit of work into making the project easier to contribute to.
