### ISSUE TITLE
Nested buildList() doesn't create new arrays

### ISSUE THREAD

**Issue by caseyli** [rosiejs/rosie#83]
Hi rosie team,

I'm a little new to rosie, but have been using FactoryBot for a long time. So forgive me if I'm misunderstanding how things work or if this is expected behaviour.

The basic behaviour I'm seeing is that when you have a parent factory that has a collection of children - the array of children that gets generated by buildList doesn't generate a new list every time.

Where this really becomes an issue is if you have a beforeEach say with Jest specs - where you're regenerated the parent everytime - the children don't seem to get regenerated. So if you edit the children, it gets carried over to other specs.

Here's some code that illustrates my point better:

```js
const Factory = require('rosie').Factory;

const child = Factory.define('child')
  .sequence('id')
  .attrs({
    name: 'test'
  });

const parent = Factory.define('parent')
  .sequence('id')
  .attrs({
    children: child.buildList(3)
  });

let parent1 = parent.build();
let parent2 = parent.build();

console.log("Are both parents referentially the same? ");
console.log(parent1 === parent2);
console.log("Are both parent.children referentially the same?");
console.log(parent1.children === parent2.children);

console.log("IDs before change: parent1.children[0] has an ID of " + parent1.children[0].id + " and parent2.children[0] has an ID of " + parent2.children[0].id); 

/* ONLY CHANGE parent1 */
parent1.children[0].id = 100;

console.log("IDs before change: parent1.children[0] has an ID of " + parent1.children[0].id + " and parent2.children[0] has an ID of " + parent2.children[0].id); 

let childrenList1 = child.buildList(2);
let childrenList2 = child.buildList(2);

console.log("Are both standalone children lists referentially the same?");
console.log(childrenList1 === childrenList2);
```

And here's the output

```
    Are both parents referentially the same? 
    false

    Are both parent.children referentially the same?
    true

    IDs before change: parent1.children[0] has an ID of 1 and parent2.children[0] has an ID of 1

    IDs before change: parent1.children[0] has an ID of 100 and parent2.children[0] has an ID of 100


    Are both standalone children lists referentially the same?
    false
```

So as you see, if you wanted to create two parents, and then independently edit each of its children - you wouldn't be able to.

Again, let me know if this is expected behaviour and if there is a workaround?

Thanks! Great library!

**Comment by eventualbuddha** [comment]
You can fix this by changing the definition of `parent`:

```js
const parent = Factory.define('parent')
  .sequence('id')
  .attrs({
    children: () => child.buildList(3)
  });
```

See this [jsbin](https://jsbin.com/zayetov/edit?js,console).

**Comment by caseyli** [comment]
That did it! Thanks @eventualbuddha !
