### ISSUE TITLE
Does this remain in active development?

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [rosiejs/rosie#99]
I want to use a factory library for MongoDB in NodeJS. But I want this factory library to be able to work with both the Node MongoDB driver (which I am currently using) as well as an ORM like Mongoose (which I am not currently using). Does this work with both? Also will this work with SQL ORMs? Is this in active maintenance?

**Comment by eventualbuddha** [comment]
I don't know whether this library would be suitable for the use cases you outlined.

> Is this in active maintenance?

I think a fair answer to that question is "no", insofar as there isn't really any new work being done on it that isn't driven by PRs and issues. If there's a bugfix or documentation PR I know I'd be happy to review it. For new features, as long as it's not a breaking change and it makes sense with the existing feature set, such things could be accepted. But I wouldn't expect to see a lot of changes in this library over time, no.
